version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/node:current

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build application
          command: yarn build

  test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test

  build_and_push_docker:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker images
          command: |
            docker build -t web ./web
            docker build -t api ./api
      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 976193228961.dkr.ecr.us-east-1.amazonaws.com
      - run:
          name: Push Docker images to ECR
          command: |
            docker tag web:latest 976193228961.dkr.ecr.us-east-1.amazonaws.com/web:latest
            docker tag api:latest 976193228961.dkr.ecr.us-east-1.amazonaws.com/api:latest
            docker push 976193228961.dkr.ecr.us-east-1.amazonaws.com/web:latest
            docker push 976193228961.dkr.ecr.us-east-1.amazonaws.com/api:latest

workflows:
  version: 2
  # Build and test yarn on every branch. But only build and push Docker images on the main branch.
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build_and_push_docker:
          requires:
            - test
          filters:
            branches:
              only: main